# Generated by Django 4.2.11 on 2024-03-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacherfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='teacherform/')),
                ('ContactNo', models.IntegerField(max_length=20)),
                ('Emailid', models.EmailField(max_length=254)),
                ('Expierence', models.IntegerField(max_length=10)),
                ('teachingsubject', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='front',
        ),
    ]
