# Generated by Django 4.2.11 on 2024-03-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_teacherfo_delete_front'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherfo',
            name='ContactNo',
            field=models.IntegerField(),
        ),
    ]
