# Generated by Django 4.2.11 on 2024-03-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_teacherfo_contactno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherfo',
            name='Expierence',
            field=models.IntegerField(),
        ),
    ]
