# Generated by Django 4.2.11 on 2024-03-17 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_teacherfo_expierence'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teacherfo',
            new_name='teachersrModel',
        ),
    ]
