# Generated by Django 4.2.11 on 2024-03-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_teacherfo_teachersrmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseimage', models.ImageField(upload_to='imagesh/')),
                ('coursename', models.CharField(max_length=100)),
                ('courseduration', models.CharField(max_length=60)),
                ('coursedetails', models.CharField(max_length=300)),
                ('coursefee', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
