# Generated by Django 4.2.11 on 2024-03-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_teachersrmodel_teachername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersrmodel',
            name='teacherName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
