# Generated by Django 4.2.11 on 2024-03-17 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_teachersrmodel_teachername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachersrmodel',
            name='teacherName',
        ),
    ]
