# Generated by Django 4.2.11 on 2024-03-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_teachersrmodel_teachername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersrmodel',
            name='teacherName',
            field=models.CharField(max_length=100),
        ),
    ]
