# Generated by Django 4.2.11 on 2024-03-17 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_teachersrmodel_teachername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachersrmodel',
            old_name='teacherName',
            new_name='Name',
        ),
    ]
