# Generated by Django 4.2.11 on 2024-03-17 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_teachername_teachersrmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachersrmodel',
            name='Name',
        ),
    ]
