# Generated by Django 4.2.11 on 2024-03-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_teachersrmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersrmodel',
            name='Name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
