# Generated by Django 4.2.11 on 2024-03-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_teachersrmodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentsrModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Image', models.ImageField(upload_to='teacherform/')),
                ('ParentNo', models.IntegerField()),
                ('Branch', models.CharField(max_length=40)),
                ('Section', models.CharField(max_length=40)),
                ('Subjects', models.CharField(max_length=200)),
            ],
        ),
    ]
